### ISSUE TITLE
ModuleNotFoundError: No module named 'meter'

### ISSUE THREAD

**Issue by Ala-Jeb** [ahlashkari/DoHlyzer#1]
When I ryn the meter/dohlyzer.py file I get the error 
""  File "./dohlyzer.py", line 8, in <module>
    from meter.flow_session import generate_session_class
ModuleNotFoundError: No module named 'meter'
""
I tried to add the meter folder to the packages but I still get errors 
Any idea please

**Comment by QianruZhou333** [comment]
you need to put the dir to the `DoHlyzer-master` to the PYTHONPATH in your system, let python know where your project is. If your sys is mac, do the following:

`# vi ~/.bash_profile`
add `export PYTHONPATH=$PYTHONPATH:[the dir to your DoHlyzer-master folder]`  to the file
`$ source ~/.bash_profile`
