### ISSUE TITLE
Not able to import flow session from meter

### ISSUE THREAD

**Issue by Prajwal056** [ahlashkari/DoHlyzer#5]
C:\Users\hp\Desktop\DoHlyzer-master\meter>python3 dohlyzer.py -n eth0 -c ./output.csv
Traceback (most recent call last):
  File "dohlyzer.py", line 8, in <module>
    from meter.flow_session import *
ModuleNotFoundError: No module named 'meter'

**Comment by yulduzkhodjaeva** [comment]
In my case, I just removed the "meter" from the files where error popped up. For instance, if the source says: "from meter.features.flow_bytes import FlowBytes", I replaced with "from features.flow_bytes import FlowBytes". Python somehow does not recognize the meter in the source code. And everything worked fine after removal.

**Comment by yulduzkhodjaeva** [comment]
> C:\Users\hp\Desktop\DoHlyzer-master\meter>python3 dohlyzer.py -n eth0 -c ./output.csv
> Traceback (most recent call last):
> File "dohlyzer.py", line 8, in
> from meter.flow_session import *
> ModuleNotFoundError: No module named 'meter'

In my case, I just removed the "meter" from the files where error popped up. For instance, if the source says: "from meter.features.flow_bytes import FlowBytes", I replaced with "from features.flow_bytes import FlowBytes". Python somehow does not recognize the meter in the source code. And everything worked fine after removal.
